version: 2

updates:
  - package-ecosystem: npm
    directories:
      - /
      - /apps/playground
      - /apps/rsc-fixture
      - /docs
      - /packages/core
      - /packages/grid
      - /packages/primitives
      - /packages/react
      - /packages/testing
      - /packages/tokens
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
