/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is generated by Next.js. It is committed in this fixture so typecheck can
// run before build; the runner also accepts the generated equivalent.
